language: rust
cache: cargo
sudo: true
rust:
- stable
- beta
- nightly
os:
- linux
- osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - export RUST_BACKTRACE=1
  - cargo test --manifest-path=librocksdb-sys/Cargo.toml
  - cargo test

cache:
  directories:
    - $HOME/.cache/
