[package]
name = "emerald-rocksdb"
description = "Rust wrapper for Facebook's RocksDB embeddable database used in Emerald Project"
version = "0.10.0"
authors = ["Constantine r8d8@etcdev.io"]
license = "Apache-2.0"
keywords = ["database", "embedded", "LSM-tree", "persistence"]
homepage = "https://github.com/r8d8/rust-rocksdb"
exclude = [
    ".gitignore",
    ".travis.yml",
    "deploy.sh",
    "test/**/*",
]

[features]
default = []
valgrind = []

[dependencies]
libc = "0.2"
emerald_librocksdb-sys = { path = "librocksdb-sys", version = "0.5.2" }
